on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: main
jobs:
  windows:
    name: Windows
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: ./install.dependencies.cmd
      working-directory: build/windows

    - name: Build ImageMagick.FredsScripts.NET (Test)
      run: './build.cmd Test'
      working-directory: build/windows

    - name: Test ImageMagick.FredsScripts.NET
      run: './test.cmd'
      working-directory: build/windows

    - name: Build ImageMagick.FredsScripts.NET (Release)
      run: './build.cmd Release'
      working-directory: build/windows

    - name: Publish ImageMagick.FredsScripts.NET
      run: './publish.cmd'
      working-directory: publish

    - name: Upload libraries
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: publish/nupkg
