on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

name: master
jobs:
  windows:
    name: Windows
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: ./install.dependencies.cmd
      working-directory: build/windows

    - name: Build FredsImageMagickScripts.NET (Test)
      run: './build.FredsImageMagickScripts.NET.cmd Test'
      working-directory: build/windows

    - name: Test FredsImageMagickScripts.NET
      run: './test.FredsImageMagickScripts.NET.cmd'
      working-directory: build/windows

    - name: Build FredsImageMagickScripts.NET (Release)
      run: './build.FredsImageMagickScripts.NET.cmd Release'
      working-directory: build/windows